# Generated by Django 3.1 on 2020-08-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
